package system.ticketing.utilities.enums;

/**
 * Created by Ncube on 2/5/17.
 */
public enum TransactionType {
    NONE,
    BALANCE,
    CUSTOMER_INFO,
    REVERSAL,
    ALERT,
    ARREARS_IMPORT,
    ARREARS_EXPORT,
    CREDIT_TOKEN,
    TEST_TOKEN,
    LAST_TOKEN,
    VEND_ADVICE,
    CREDIT_TRANSFER_TOKEN,
    REPLACEMENT_TOKEN_ADVICE,
    KEY_CHANGE_TOKEN,
    FREE_TOKEN,
    VERIFY_TOKEN,
    FAULT_REPORT,
    UTILITY_CASH_DEPOSIT,
    VENDOR_CASH_DEPOSIT,
    VENDOR_CREDIT_TRANSFER,
    ADJUSTMENT
}
